/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/W9McxCpCkzR
 */
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table
} from '@/components/ui/table'
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu
} from '@/components/ui/dropdown-menu'

export default function deliroutetwo () {
  return (
    <main className='flex flex-col min-h-screen p-4 md:p-6'>
      <h1 className='text-2xl md:text-3xl font-semibold mb-4'>
        Manage Delivery Routes
      </h1>
      <div className='flex flex-col md:flex-row items-center gap-4 mb-4'>
        <Input
          className='flex-grow bg-white shadow-none appearance-none pl-8 mb-2 md:mb-0'
          placeholder='Search routes...'
          type='search'
        />
        <Button className='ml-auto md:ml-0 bg-black text-white'>
          Add New Route
        </Button>
      </div>
      <div className='overflow-x-auto'>
        <div className='border shadow-sm rounded-lg min-w-full p-2 bg-white'>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Status</TableHead>
                <TableHead>Route ID</TableHead>
                <TableHead>Start Point</TableHead>
                <TableHead>End Point</TableHead>
                <TableHead>Estimated Travel Time</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>In Progress</TableCell>
                <TableCell>Route #001</TableCell>
                <TableCell>1234 Main St. Anytown, USA</TableCell>
                <TableCell>7890 Elm St. Somewhere, USA</TableCell>
                <TableCell>2h 30m</TableCell>
                <TableCell className='text-right'>
                  <Button size='icon' variant='ghost'>
                    <IconEdit className='w-4 h-4' />
                  </Button>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button size='icon' variant='ghost'>
                        <IconMorehorizontal className='w-4 h-4' />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align='end'>
                      <DropdownMenuItem>Mark as Completed</DropdownMenuItem>
                      <DropdownMenuItem>Mark as In Progress</DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>In Progress</TableCell>
                <TableCell>Route #001</TableCell>
                <TableCell>1234 Main St. Anytown, USA</TableCell>
                <TableCell>7890 Elm St. Somewhere, USA</TableCell>
                <TableCell>2h 30m</TableCell>
                <TableCell className='text-right'>
                  <Button size='icon' variant='ghost'>
                    <IconEdit className='w-4 h-4' />
                  </Button>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button size='icon' variant='ghost'>
                        <IconMorehorizontal className='w-4 h-4' />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align='end'>
                      <DropdownMenuItem>Mark as Completed</DropdownMenuItem>
                      <DropdownMenuItem>Mark as In Progress</DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>In Progress</TableCell>
                <TableCell>Route #001</TableCell>
                <TableCell>1234 Main St. Anytown, USA</TableCell>
                <TableCell>7890 Elm St. Somewhere, USA</TableCell>
                <TableCell>2h 30m</TableCell>
                <TableCell className='text-right'>
                  <Button size='icon' variant='ghost'>
                    <IconEdit className='w-4 h-4' />
                  </Button>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button size='icon' variant='ghost'>
                        <IconMorehorizontal className='w-4 h-4' />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align='end'>
                      <DropdownMenuItem>Mark as Completed</DropdownMenuItem>
                      <DropdownMenuItem>Mark as In Progress</DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Completed</TableCell>
                <TableCell>Route #002</TableCell>
                <TableCell>4567 Oak St. Thiscity, USA</TableCell>
                <TableCell>3210 Pine St. Thatcity, USA</TableCell>
                <TableCell>1h 45m</TableCell>
                <TableCell className='text-right'>
                  <Button size='icon' variant='ghost'>
                    <IconEdit className='w-4 h-4' />
                  </Button>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button size='icon' variant='ghost'>
                        <IconMorehorizontal className='w-4 h-4' />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent align='end'>
                      <DropdownMenuItem>Mark as Completed</DropdownMenuItem>
                      <DropdownMenuItem>Mark as In Progress</DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </main>
  )
}

function IconMorehorizontal (prop: any) {
  return (
    <svg
      {...prop}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      stroke-width='2'
      stroke-linecap='round'
      stroke-linejoin='round'
    >
      <circle cx='12' cy='12' r='1' />
      <circle cx='19' cy='12' r='1' />
      <circle cx='5' cy='12' r='1' />
    </svg>
  )
}

function IconEdit (prop: any) {
  return (
    <svg
      {...prop}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      stroke-width='2'
      stroke-linecap='round'
      stroke-linejoin='round'
    >
      <path d='M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5' />
      <polyline points='14 2 14 8 20 8' />
      <path d='M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z' />
    </svg>
  )
}
