/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/h1waJBvMN9I
 */
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table
} from '@/components/ui/table'
import {
  DropdownMenuTrigger,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu
} from '@/components/ui/dropdown-menu'

export default function deliva () {
  return (
    <main className='flex flex-col min-h-screen p-4 md:p-6'>
      <h1 className='text-2xl font-semibold mb-4'>Manage Deliveries</h1>
      <div className='flex items-center gap-4 mb-4'>
        <Input
          className='flex-grow bg-white shadow-none appearance-none pl-8'
          placeholder='Search deliveries...'
          type='search'
        />
        <Button className='ml-auto bg-black text-white'>
          Add New Delivery
        </Button>
      </div>
      <div className='border shadow-sm rounded-lg p-2 bg-white'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Status</TableHead>
              <TableHead>Recipient</TableHead>
              <TableHead>Delivery Address</TableHead>
              <TableHead>Delivery Date</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>In Transit</TableCell>
              <TableCell>John Doe</TableCell>
              <TableCell>1234 Main St. Anytown, USA</TableCell>
              <TableCell>2023-11-25</TableCell>
              <TableCell className='text-right'>
                <Button size='icon' variant='ghost'>
                  <IconEdit className='w-4 h-4' />
                </Button>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <IconMorehorizontal className='w-4 h-4' />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Mark as Delivered</DropdownMenuItem>
                    <DropdownMenuItem>Mark as In Transit</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>In Transit</TableCell>
              <TableCell>John Doe</TableCell>
              <TableCell>1234 Main St. Anytown, USA</TableCell>
              <TableCell>2023-11-25</TableCell>
              <TableCell className='text-right'>
                <Button size='icon' variant='ghost'>
                  <IconEdit className='w-4 h-4' />
                </Button>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <IconMorehorizontal className='w-4 h-4' />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Mark as Delivered</DropdownMenuItem>
                    <DropdownMenuItem>Mark as In Transit</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>In Transit</TableCell>
              <TableCell>John Doe</TableCell>
              <TableCell>1234 Main St. Anytown, USA</TableCell>
              <TableCell>2023-11-25</TableCell>
              <TableCell className='text-right'>
                <Button size='icon' variant='ghost'>
                  <IconEdit className='w-4 h-4' />
                </Button>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <IconMorehorizontal className='w-4 h-4' />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Mark as Delivered</DropdownMenuItem>
                    <DropdownMenuItem>Mark as In Transit</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Delivered</TableCell>
              <TableCell>Jane Doe</TableCell>
              <TableCell>7890 Elm St. Somewhere, USA</TableCell>
              <TableCell>2023-11-22</TableCell>
              <TableCell className='text-right'>
                <Button size='icon' variant='ghost'>
                  <IconEdit className='w-4 h-4' />
                </Button>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size='icon' variant='ghost'>
                      <IconMorehorizontal className='w-4 h-4' />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align='end'>
                    <DropdownMenuItem>Mark as Delivered</DropdownMenuItem>
                    <DropdownMenuItem>Mark as In Transit</DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </main>
  )
}

function IconEdit (prop: any) {
  return (
    <svg
      {...prop}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      stroke-width='2'
      stroke-linecap='round'
      stroke-linejoin='round'
    >
      <path d='M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5' />
      <polyline points='14 2 14 8 20 8' />
      <path d='M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z' />
    </svg>
  )
}

function IconMorehorizontal (prop: any) {
  return (
    <svg
      {...prop}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      stroke-width='2'
      stroke-linecap='round'
      stroke-linejoin='round'
    >
      <circle cx='12' cy='12' r='1' />
      <circle cx='19' cy='12' r='1' />
      <circle cx='5' cy='12' r='1' />
    </svg>
  )
}
