/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/d3rEjkQEqUC
 */
import Link from 'next/link'
import { Avatar } from '@/components/ui/avatar'
import { CardTitle, CardHeader, CardContent, Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import {
  SelectValue,
  SelectTrigger,
  SelectLabel,
  SelectItem,
  SelectGroup,
  SelectContent,
  Select
} from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { Button } from '@/components/ui/button'

export default function estimatee () {
  return (
    <div className='flex flex-col h-full bg-gray-100 dark:bg-gray-900'>
      <div className='flex flex-1 md:flex-row md:space-x-8'>
        <main className='flex-1 p-8 bg-white rounded-lg shadow-lg m-4'>
          <Card className='rounded-lg shadow-lg'>
            <CardHeader className='p-6 bg-gray-100 dark:bg-gray-700'>
              <CardTitle className='text-2xl font-bold text-gray-900 dark:text-gray-100'>
                Estimate
              </CardTitle>
            </CardHeader>
            <CardContent className='p-6'>
              <form className='space-y-6'>
                <Input
                  className='w-full border border-gray-300 dark:border-gray-700 rounded-lg px-4 py-3'
                  placeholder='Pickup details'
                  type='text'
                />
                <Input
                  className='w-full border border-gray-300 dark:border-gray-700 rounded-lg px-4 py-3'
                  placeholder='Delivery details'
                  type='text'
                />
                <Select className='w-full border border-gray-300 dark:border-gray-700 rounded-lg px-4 py-3'>
                  <SelectTrigger className='w-full'>
                    <SelectValue placeholder='Shipment type' />
                  </SelectTrigger>
                  <SelectContent className='w-full bg-[#0F2B48] p-4 rounded text-white'>
                    <SelectGroup>
                      <SelectLabel>Shipment Types</SelectLabel>
                      <SelectItem value='type1'>Type 1</SelectItem>
                      <SelectItem value='type2'>Type 2</SelectItem>
                    </SelectGroup>
                  </SelectContent>
                </Select>
                <Input
                  className='w-full border border-gray-300 dark:border-gray-700 rounded-lg px-4 py-3'
                  placeholder='Weight'
                  type='number'
                />
                <Input
                  className='w-full border border-gray-300 dark:border-gray-700 rounded-lg px-4 py-3'
                  placeholder='Additional services'
                  type='text'
                />
                <Button className='w-full bg-blue-600 hover:bg-blue-700 text-white rounded-lg py-3'>
                  Submit
                </Button>
              </form>
            </CardContent>
          </Card>
        </main>
      </div>
      <div className='flex flex-1 md:flex-row md:space-x-8'>
        <main className='flex-1 p-8 bg-white rounded-lg shadow-lg m-4'>
          <Card className='rounded-lg shadow-lg'>
            <CardHeader className='p-6 bg-gray-100 dark:bg-gray-700'>
              <CardTitle className='text-2xl font-bold text-gray-900 dark:text-gray-100'>
                Estimated Costs
              </CardTitle>
            </CardHeader>
            <CardContent className='grid gap-2 p-6 rounded-2xl m-4'>
              <div className='flex justify-between'>
                <div>Service Fee</div>
                <div>$100.00</div>
              </div>
              <div className='flex justify-between'>
                <div>Weight Fee</div>
                <div>$50.00</div>
              </div>
              <Separator />
              <div className='flex justify-between text-lg font-medium'>
                <div>Total</div>
                <div>$150.00</div>
              </div>
            </CardContent>
          </Card>
          <Button className='w-full mt-4 bg-blue-600 hover:bg-blue-700 text-white rounded-lg py-3'>
            Submit Estimate Request
          </Button>
        </main>
      </div>
    </div>
  )
}

function IconPackage2 (prop: any) {
  return (
    <svg
      {...prop}
      xmlns='http://www.w3.org/2000/svg'
      width='24'
      height='24'
      viewBox='0 0 24 24'
      fill='none'
      stroke='currentColor'
      stroke-width='2'
      stroke-linecap='round'
      stroke-linejoin='round'
    >
      <path d='M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z' />
      <path d='m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9' />
      <path d='M12 3v6' />
    </svg>
  )
}
