/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tjZVaynNMrL
 */
import Link from 'next/link'
import { Button } from '@/components/ui/button'

export default function addfunds () {
  return (
    <div className='grid h-screen min-h-screen w-full overflow-hidden md:grid-cols-2'>
      <div className='flex flex-col h-full bg-gradient-to-r from-blue-500 to-purple-500 p-8'>
        <div className='mb-auto'>
          <h1 className='text-white text-4xl font-bold'>Add Funds</h1>
          <p className='text-white text-lg mt-2'>
            Increase your wallet balance
          </p>
        </div>
        <div className='text-white text-sm'>
          <Link className='flex items-center gap-2 font-semibold' href='#'>
            <svg
              className=' h-6 w-6 text-white'
              fill='none'
              height='24'
              stroke='currentColor'
              strokeLinecap='round'
              strokeLinejoin='round'
              strokeWidth='2'
              viewBox='0 0 24 24'
              width='24'
              xmlns='http://www.w3.org/2000/svg'
            >
              <path d='m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z' />
              <polyline points='9 22 9 12 15 12 15 22' />
            </svg>
            <span>Back to Home</span>
          </Link>
        </div>
      </div>
      <div className='flex flex-col bg-white p-8 overflow-auto'>
        <div className='flex flex-col gap-6'>
          <h2 className='text-2xl font-semibold'>
            Your Current Wallet Balance: $5000.00
          </h2>
          <form className='flex flex-col gap-6'>
            <label className='text-lg font-medium'>Amount to add:</label>
            <input
              aria-label='Amount'
              className='border border-gray-300 rounded-lg p-4 text-lg'
              placeholder='Enter amount'
              type='text'
            />
            <Button
              className='w-full md:w-auto bg-blue-500 text-white py-3 text-lg'
              type='submit'
            >
              Add Funds
            </Button>
          </form>
        </div>
      </div>
    </div>
  )
}
