/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tGfNOlPsEsj
 */
'use client;'
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectLabel, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export default function Deliver() {
  return (
    <div className="flex h-screen w-full">
      <aside className="w-80 border-r p-4 overflow-auto dark:bg-gray-800 dark:border-gray-700">
        <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-200">Delivery Routes</h2>
        <form>
          <fieldset className="mb-4">
            <legend className="font-medium mb-2 text-gray-800 dark:text-gray-200">Filter by Date</legend>
            <Input className="w-full dark:bg-gray-700 dark:text-white" type="date" />
          </fieldset>
          <fieldset className="mb-4">
            <legend className="font-medium mb-2 text-gray-800 dark:text-gray-200">Filter by Driver</legend>
            <Select>
              <SelectTrigger>
                <SelectValue className="dark:bg-gray-700 dark:text-white" placeholder="Select a driver" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectLabel className="dark:text-gray-200">Drivers</SelectLabel>
                  <SelectItem value="driver1">Driver 1</SelectItem>
                  <SelectItem value="driver2">Driver 2</SelectItem>
                  <SelectItem value="driver3">Driver 3</SelectItem>
                  <SelectItem value="driver4">Driver 4</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </fieldset>
          <Button className="w-full bg-green-500 hover:bg-green-600 text-white" type="submit">
            Apply Filters
          </Button>
        </form>
        <h3 className="text-xl font-semibold my-4 text-gray-800 dark:text-gray-200">Delivery Details</h3>
        <div className="space-y-4">
          <div className="p-4 border rounded-md dark:border-gray-700 bg-white dark:bg-gray-800">
            <h4 className="font-semibold mb-2 text-gray-800 dark:text-gray-200">Delivery 1</h4>
            <p className="text-gray-800 dark:text-gray-200">Driver: Driver 1</p>
            <p className="text-gray-800 dark:text-gray-200">Date: 2023-11-16</p>
            <p className="text-gray-800 dark:text-gray-200">Status: In Transit</p>
          </div>
          <div className="p-4 border rounded-md dark:border-gray-700 bg-white dark:bg-gray-800">
            <h4 className="font-semibold mb-2 text-gray-800 dark:text-gray-200">Delivery 2</h4>
            <p className="text-gray-800 dark:text-gray-200">Driver: Driver 2</p>
            <p className="text-gray-800 dark:text-gray-200">Date: 2023-11-16</p>
            <p className="text-gray-800 dark:text-gray-200">Status: Delivered</p>
          </div>
          <div className="p-4 border rounded-md dark:border-gray-700 bg-white dark:bg-gray-800">
            <h4 className="font-semibold mb-2 text-gray-800 dark:text-gray-200">Delivery 3</h4>
            <p className="text-gray-800 dark:text-gray-200">Driver: Driver 3</p>
            <p className="text-gray-800 dark:text-gray-200">Date: 2023-11-16</p>
            <p className="text-gray-800 dark:text-gray-200">Status: In Transit</p>
          </div>
        </div>
      </aside>
      <div className="flex-1 p-6">
        <h2 className="text-2xl font-semibold mb-4 text-gray-800 dark:text-gray-200">Interactive Delivery Map</h2>
        <img
          alt="Interactive map displaying delivery routes"
          className="object-cover w-full h-full rounded-lg shadow-lg"
          height="500"
          src="/placeholder.svg"
          style={{
            aspectRatio: "500/500",
            objectFit: "cover",
          }}
          width="500"
        />
        <div className="grid grid-cols-2 gap-6 mt-6">
          <div className="bg-white p-4 rounded-lg shadow-lg dark:bg-gray-800">
            <h3 className="font-medium mb-2 text-gray-800 dark:text-gray-200">Total Deliveries</h3>
            <p className="text-4xl font-bold text-gray-800 dark:text-gray-200">120</p>
          </div>
          <div className="bg-white p-4 rounded-lg shadow-lg dark:bg-gray-800">
            <h3 className="font-medium mb-2 text-gray-800 dark:text-gray-200">Deliveries In Transit</h3>
            <p className="text-4xl font-bold text-gray-800 dark:text-gray-200">45</p>
          </div>
        </div>
      </div>
    </div>
  )
}
