/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dtODiSx7eZg
 */
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { CardTitle, CardHeader, Card } from '@/components/ui/card'

export default function Deli () {
  return (
    <div className='grid h-screen min-h-screen w-full overflow-hidden lg:grid-cols-[280px_1fr]'>
      <div className='hidden border-r bg-zinc-100/40 lg:block dark:bg-zinc-800/40'>
        <div className='flex h-[60px] items-center border-b px-6'>
          <Link className='flex items-center gap-2 font-semibold' href='#'>
            <svg
              className=' h-6 w-6'
              fill='none'
              height='24'
              stroke='currentColor'
              strokeLinecap='round'
              strokeLinejoin='round'
              strokeWidth='2'
              viewBox='0 0 24 24'
              width='24'
              xmlns='http://www.w3.org/2000/svg'
            >
              <path d='M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z' />
              <path d='m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9' />
              <path d='M12 3v6' />
            </svg>
            <span className=''>Logistics Inc</span>
          </Link>
        </div>
        <div className='flex-1 overflow-auto py-2'>
          <nav className='grid items-start px-4 text-sm font-medium'>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <polygon points='3 6 9 3 15 6 21 3 21 18 15 21 9 18 3 21' />
                <line x1='9' x2='9' y1='3' y2='18' />
                <line x1='15' x2='15' y1='6' y2='21' />
              </svg>
              Routes
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <path d='m7.5 4.27 9 5.15' />
                <path d='M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z' />
                <path d='m3.3 7 8.7 5 8.7-5' />
                <path d='M12 22V12' />
              </svg>
              Packages
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2' />
                <circle cx='9' cy='7' r='4' />
                <path d='M22 21v-2a4 4 0 0 0-3-3.87' />
                <path d='M16 3.13a4 4 0 0 1 0 7.75' />
              </svg>
              Drivers
            </Link>
            <Link
              className='flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
              href='#'
            >
              <svg
                className=' h-4 w-4'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <rect height='18' rx='2' ry='2' width='18' x='3' y='4' />
                <line x1='16' x2='16' y1='2' y2='6' />
                <line x1='8' x2='8' y1='2' y2='6' />
                <line x1='3' x2='21' y1='10' y2='10' />
              </svg>
              Schedule
            </Link>
          </nav>
        </div>
      </div>
      <div className='flex flex-col'>
        <header className='flex h-14 lg:h-[60px] items-center gap-4 border-b bg-zinc-100/40 px-6 dark:bg-zinc-800/40'>
          <Link className='lg:hidden' href='#'>
            <svg
              className=' h-6 w-6'
              fill='none'
              height='24'
              stroke='currentColor'
              strokeLinecap='round'
              strokeLinejoin='round'
              strokeWidth='2'
              viewBox='0 0 24 24'
              width='24'
              xmlns='http://www.w3.org/2000/svg'
            >
              <path d='M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z' />
              <path d='m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9' />
              <path d='M12 3v6' />
            </svg>
            <span className='sr-only'>Home</span>
          </Link>
          <nav className='hidden lg:flex gap-5 ml-auto'>
            <Link className='font-semibold' href='#'>
              Home
            </Link>
            <Link className='text-zinc-500 dark:text-zinc-400' href='#'>
              Deliveries
            </Link>
            <Link className='text-zinc-500 dark:text-zinc-400' href='#'>
              Vehicles
            </Link>
            <Link className='text-zinc-500 dark:text-zinc-400' href='#'>
              Reports
            </Link>
            <Button className='text-zinc-500 dark:text-zinc-400' variant='link'>
              Logout
            </Button>
          </nav>
        </header>
        <main className='flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6'>
          <div className='w-full h-[600px] border shadow-sm rounded-lg bg-white dark:bg-zinc-800'>
            <img
              alt='Map'
              height='100%'
              src='/placeholder.svg'
              style={{
                aspectRatio: '100%/100%',
                objectFit: 'cover'
              }}
              width='100%'
            />
          </div>
          <div className='flex justify-between items-center'>
            <h2 className='text-lg font-semibold'>Delivery Status</h2>
          </div>
          <div className='grid grid-cols-2 gap-4 md:grid-cols-4'>
            <Card>
              <CardHeader className='flex items-center justify-between'>
                <CardTitle className='text-sm font-medium'>Delivered</CardTitle>
                <svg
                  className=' w-4 h-4 text-green-500'
                  fill='none'
                  height='24'
                  stroke='currentColor'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  strokeWidth='2'
                  viewBox='0 0 24 24'
                  width='24'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <polyline points='20 6 9 17 4 12' />
                </svg>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className='flex items-center justify-between'>
                <CardTitle className='text-sm font-medium'>
                  In Transit
                </CardTitle>
                <svg
                  className=' w-4 h-4 text-yellow-500'
                  fill='none'
                  height='24'
                  stroke='currentColor'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  strokeWidth='2'
                  viewBox='0 0 24 24'
                  width='24'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <path d='M5 18H3c-.6 0-1-.4-1-1V7c0-.6.4-1 1-1h10c.6 0 1 .4 1 1v11' />
                  <path d='M14 9h4l4 4v4c0 .6-.4 1-1 1h-2' />
                  <circle cx='7' cy='18' r='2' />
                  <path d='M15 18H9' />
                  <circle cx='17' cy='18' r='2' />
                </svg>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className='flex items-center justify-between'>
                <CardTitle className='text-sm font-medium'>Delayed</CardTitle>
                <svg
                  className=' w-4 h-4 text-red-500'
                  fill='none'
                  height='24'
                  stroke='currentColor'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  strokeWidth='2'
                  viewBox='0 0 24 24'
                  width='24'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <circle cx='12' cy='12' r='10' />
                  <polyline points='12 6 12 12 16 14' />
                </svg>
              </CardHeader>
            </Card>
            <Card>
              <CardHeader className='flex items-center justify-between'>
                <CardTitle className='text-sm font-medium'>Scheduled</CardTitle>
                <svg
                  className=' w-4 h-4 text-blue-500'
                  fill='none'
                  height='24'
                  stroke='currentColor'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  strokeWidth='2'
                  viewBox='0 0 24 24'
                  width='24'
                  xmlns='http://www.w3.org/2000/svg'
                >
                  <rect height='18' rx='2' ry='2' width='18' x='3' y='4' />
                  <line x1='16' x2='16' y1='2' y2='6' />
                  <line x1='8' x2='8' y1='2' y2='6' />
                  <line x1='3' x2='21' y1='10' y2='10' />
                </svg>
              </CardHeader>
            </Card>
          </div>
        </main>
      </div>
    </div>
  )
}
