/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bglikdYrZIi
 */
'use client'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table
} from '@/components/ui/table'
import { useState } from 'react'
import Transaction from '../component/wallet/Transaction'
import AddFund from '../component/wallet/AddFund'

export default function Wallet () {
  const [currentPage, setCurrentPage] = useState('transactions')

  const handleClick = (page: string) => {
    setCurrentPage(page)
  }

  return (
    <div className='grid h-screen min-h-screen w-full md:grid-cols-[280px_1fr]'>
      <div className='border-r bg-zinc-100/40 md:block dark:bg-zinc-800/40'>
        <div className='flex h-full max-h-screen flex-col gap-2'>
          <div className='flex h-[60px] items-center border-b px-6'>
            <Link className='flex items-center gap-2 font-semibold' href='#'>
              <svg
                className=' h-6 w-6'
                fill='none'
                height='24'
                stroke='currentColor'
                strokeLinecap='round'
                strokeLinejoin='round'
                strokeWidth='2'
                viewBox='0 0 24 24'
                width='24'
                xmlns='http://www.w3.org/2000/svg'
              >
                <path d='M21 12V7H5a2 2 0 0 1 0-4h14v4' />
                <path d='M3 5v14a2 2 0 0 0 2 2h16v-5' />
                <path d='M18 12a2 2 0 0 0 0 4h4v-4Z' />
              </svg>
              <span className=''>Wallet</span>
            </Link>
          </div>
          <div className='flex-1 overflow-auto py-2'>
            <nav className='grid items-start px-4 text-sm font-medium'>
              <Link
                className={`flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all ${
                  currentPage === 'transactions'
                    ? 'text-zinc-900 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
                    : 'hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
                }`}
                href='#'
                onClick={() => handleClick('transactions')}
              >
                Transactions
              </Link>
              <Link
                className={`flex items-center gap-3 rounded-lg px-3 py-2 text-zinc-500 transition-all ${
                  currentPage === 'addFunds'
                    ? 'text-zinc-900 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
                    : 'hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-zinc-50'
                }`}
                href='#'
                onClick={() => handleClick('addFunds')}
              >
                Add Funds
              </Link>
            </nav>
          </div>
        </div>
      </div>
      <div className='flex-1 overflow-auto py-2'>
        {currentPage === 'transactions' && <Transaction />}
        {currentPage === 'addFunds' && <AddFund />}
      </div>
    </div>
  )
}
